export default function sitemap() {
  const baseUrl = 'https://www.nataliachiva.com';
  
  const routes = [
    '',
    '/terapia',
    '/consultas-online',
    '/consultas-presenciales',
    '/blog',
    '/contacto',
    '/aprende',
    '/recursos-gratuitos',
    '/tests-psicologicos',
    '/calculadoras-psicologicas',
    '/guias-interactivas',
    '/recursos-autoayuda',
    '/test-ansiedad',
    '/test-depresion',
    '/test-estres-laboral',
    '/test-autoestima',
    '/test-salud-mental',
    '/test-pareja',
    '/calculadora-burnout',
    '/medidor-estres',
    '/evaluador-relacion',
    '/guia-5-dias-ansiedad',
    '/plan-7-dias-autoestima',
    '/ejercicios-respiracion',
    '/relajacion-progresiva',
    '/diario-emociones',
    '/registro-pensamientos',
    '/mindfulness-guiado',
    '/tecnicas-afrontamiento',
    '/psicologo-ansiedad-santander',
    '/terapia-pareja-santander',
    '/psicologo-infantil-santander',
    '/psicologo-online-santander',
    '/aviso-legal',
    '/politica-privacidad',
    '/cookies',
  ];

  const blogPosts = [
    '/blog/como-superar-la-ansiedad',
    '/blog/sintomas-depresion',
    '/blog/terapia-pareja-cuando-necesaria',
    '/blog/gestion-estres-trabajo',
    '/blog/autoestima-como-mejorarla',
    '/blog/terapia-online-beneficios',
    '/blog/inteligencia-emocional',
    '/blog/ataques-panico-que-hacer',
    '/blog/comunicacion-pareja',
  ];

  const aprendePages = [
    '/aprende/ansiedad',
    '/aprende/estres',
    '/aprende/depresion',
    '/aprende/autoestima',
    '/aprende/consecucion-metas',
    '/aprende/agorafobia',
    '/aprende/estres-laboral',
    '/aprende/duelo',
    '/aprende/fobias',
    '/aprende/parentalidad-positiva',
  ];

  const cityPages = [
    '/terapia-online-madrid',
    '/terapia-online-barcelona',
    '/terapia-online-valencia',
    '/terapia-online-sevilla',
    '/terapia-online-zaragoza',
    '/terapia-online-malaga',
    '/terapia-online-murcia',
    '/terapia-online-palma',
    '/terapia-online-bilbao',
    '/terapia-online-alicante',
    '/terapia-online-cordoba',
    '/terapia-online-valladolid',
    '/terapia-online-vigo',
    '/terapia-online-gijon',
    '/terapia-online-granada',
    '/terapia-online-a-coruna',
    '/terapia-online-vitoria',
    '/terapia-online-oviedo',
    '/terapia-online-pamplona',
    '/terapia-online-salamanca',
    '/terapia-online-logrono',
    '/terapia-online-burgos',
    '/terapia-online-albacete',
    '/terapia-online-santander',
    '/terapia-online-castellon',
    '/terapia-online-leon',
    '/terapia-online-cadiz',
    '/terapia-online-huelva',
    '/terapia-online-badajoz',
    '/terapia-online-tarragona',
  ];

  const allRoutes = [...routes, ...blogPosts, ...aprendePages, ...cityPages];

  return allRoutes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route.includes('/blog/') || route.includes('/aprende/') ? 'weekly' : 'monthly',
    priority: route === '' ? 1 : route.includes('/aprende/') || route.includes('/blog/') ? 0.8 : 0.9,
  }));
}
